#include <stdbool.h>
#include <stdint.h>
#include <kernel/interrupts/intrStructs.h>

#ifndef PROCESS_H
#define PROCESS_H

struct Process {
    uint32_t procID;

    // runqueue
    struct Process* next;

    // flags
    bool kernel;
    bool v8086;

    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CONTEXT SWITCH CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS

    // integral information per process
    uint32_t cr3; // pointer to page table
    uint32_t kesp; // kernel stack 
    uint32_t krnlStackTop;
} __attribute__((packed));

extern struct Process procHead;
extern struct Process* current;

uint32_t createNewProcess(bool kernel, bool v8086, uint32_t cr3, uint32_t kernelStackTop, uint32_t startEip, uint32_t usrEspIfNeeded);

#endif