#include <stdbool.h>
#include <stdint.h>
#include <kernel/interrupts/intrStructs.h>

#ifndef PROCESS_H
#define PROCESS_H

// status: 0: normal
// status: 1: KEYBOARD_WAIT

struct Process {
    uint32_t procID;

    // runqueue
    struct Process* next;

    // flags
    bool kernel;
    bool v8086;

    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CONTEXT SWITCH CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS
    // WHEN YOU CHANGE THIS STRUCT, YOU HAVE TO CHANGE THE ASSEMBLY CODE AS WELL CAUSE IT RELIES ON HARDCODED OFFSETS

    // integral information per process
    uint32_t cr3; // pointer to page table
    uint32_t kesp; // kernel stack 
    uint32_t krnlStackTop;
    bool zombie;
    uint32_t status;
    volatile uint16_t* buffer;
    int cursor;
} __attribute__((packed));

extern struct Process procHead;
extern struct Process* current;
extern bool procEnabled;
extern uint32_t procIDShowing;

uint32_t createNewProcess(bool kernel, bool v8086, uint32_t procStackDirStruct, uint32_t startEip, uint32_t usrEspIfNeeded, uint16_t usrDSIfNeeded, uint16_t usrFSIfNeeded, uint16_t usrGSIfNeeded, uint16_t usrCSIfNeeded, uint16_t usrESIfNeeded, uint16_t usrSSIfNeeded);
uint32_t createProcStackDirectoryStructure();
void deleteProcess(uint32_t pid);


#endif